# Generated by Django 4.0.2 on 2022-02-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
    ]
